export const NICE_ADJECTIVES = [
  'nett',
  'freundlich',
  'ehrlich',
  'verständnisvoll',
  'gutaussehend',
  'kompetent',
  'erfolgreich',
  'treu',
  'hilfsbereit',
  'attraktiv',
  'ehrgeizig',
  'charmant',
  'beliebt',
  'verantwortungsbewusst',
  'tierlieb',
  'gut mit Kindern',
  'sportlich',
  'gesund',
  'motiviert',
  'zielstrebig',
  'teamgeisterig',
  'witzig',
  'gepflegt',
  'hat ne richtig freshe Frise',
  'guter Geschmack',
  'richtig Dufte'
];
